//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.28 at 02:58:02 PM ICT 
//


package dev.ale.fdx.entity.messaging;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;

import dev.ale.fdx.entity.base.ExtensibleType;


/**
 * 
 *             The FlightPlanVersionChoice class allows specifying an AU flight plan version or 
 *             an ASP flight plan version. [FIXM] 
 *          
 * 
 * <p>Java class for FlightPlanVersionTypeChoiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FlightPlanVersionTypeChoiceType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fixm.aero/base/4.1}ExtensibleType">
 *       &lt;choice>
 *         &lt;element name="aspFlightPlanVersion" type="{http://www.fixm.aero/messaging/4.1}AspFlightPlanVersionTypeType" minOccurs="0"/>
 *         &lt;element name="auFlightPlanVersion" type="{http://www.fixm.aero/messaging/4.1}AuFlightPlanVersionTypeType" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlightPlanVersionTypeChoiceType", propOrder = {
    "aspFlightPlanVersion",
    "auFlightPlanVersion"
})
@Entity(name = "FlightPlanVersionTypeChoiceType")
@Table(name = "FLIGHTPLANVERSIONTYPECHOICET_0")
public class FlightPlanVersionTypeChoiceType
    extends ExtensibleType
    implements Equals, HashCode
{

    protected String aspFlightPlanVersion;
    protected Integer auFlightPlanVersion;

    /**
     * Gets the value of the aspFlightPlanVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "ASPFLIGHTPLANVERSION", length = 4096)
    public String getAspFlightPlanVersion() {
        return aspFlightPlanVersion;
    }

    /**
     * Sets the value of the aspFlightPlanVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAspFlightPlanVersion(String value) {
        this.aspFlightPlanVersion = value;
    }

    /**
     * Gets the value of the auFlightPlanVersion property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    @Basic
    @Column(name = "AUFLIGHTPLANVERSION", precision = 10, scale = 0)
    public Integer getAuFlightPlanVersion() {
        return auFlightPlanVersion;
    }

    /**
     * Sets the value of the auFlightPlanVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAuFlightPlanVersion(Integer value) {
        this.auFlightPlanVersion = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof FlightPlanVersionTypeChoiceType)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final FlightPlanVersionTypeChoiceType that = ((FlightPlanVersionTypeChoiceType) object);
        {
            String lhsAspFlightPlanVersion;
            lhsAspFlightPlanVersion = this.getAspFlightPlanVersion();
            String rhsAspFlightPlanVersion;
            rhsAspFlightPlanVersion = that.getAspFlightPlanVersion();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "aspFlightPlanVersion", lhsAspFlightPlanVersion), LocatorUtils.property(thatLocator, "aspFlightPlanVersion", rhsAspFlightPlanVersion), lhsAspFlightPlanVersion, rhsAspFlightPlanVersion)) {
                return false;
            }
        }
        {
            Integer lhsAuFlightPlanVersion;
            lhsAuFlightPlanVersion = this.getAuFlightPlanVersion();
            Integer rhsAuFlightPlanVersion;
            rhsAuFlightPlanVersion = that.getAuFlightPlanVersion();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "auFlightPlanVersion", lhsAuFlightPlanVersion), LocatorUtils.property(thatLocator, "auFlightPlanVersion", rhsAuFlightPlanVersion), lhsAuFlightPlanVersion, rhsAuFlightPlanVersion)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            String theAspFlightPlanVersion;
            theAspFlightPlanVersion = this.getAspFlightPlanVersion();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "aspFlightPlanVersion", theAspFlightPlanVersion), currentHashCode, theAspFlightPlanVersion);
        }
        {
            Integer theAuFlightPlanVersion;
            theAuFlightPlanVersion = this.getAuFlightPlanVersion();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "auFlightPlanVersion", theAuFlightPlanVersion), currentHashCode, theAuFlightPlanVersion);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
