//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.28 at 02:58:02 PM ICT 
//


package dev.ale.fdx.entity.base;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * 
 *             A reference to an area control centre, approach control unit or aerodrome control 
 *             tower using the ICAO location indicator of the atc unit, as listed in ICAO DOC 7910. 
 *             [FIXM] 
 *          
 * 
 * <p>Java class for IcaoUnitReferenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IcaoUnitReferenceType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fixm.aero/base/4.1}AtcUnitReferenceType">
 *       &lt;attribute name="locationIndicator" type="{http://www.fixm.aero/base/4.1}LocationIndicatorType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IcaoUnitReferenceType")
@Entity(name = "IcaoUnitReferenceType")
@Table(name = "ICAOUNITREFERENCETYPE")
public class IcaoUnitReferenceType
    extends AtcUnitReferenceType
    implements Equals, HashCode
{

    @XmlAttribute(name = "locationIndicator")
    protected String locationIndicator;

    /**
     * Gets the value of the locationIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "LOCATIONINDICATOR", length = 4096)
    public String getLocationIndicator() {
        return locationIndicator;
    }

    /**
     * Sets the value of the locationIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationIndicator(String value) {
        this.locationIndicator = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof IcaoUnitReferenceType)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final IcaoUnitReferenceType that = ((IcaoUnitReferenceType) object);
        {
            String lhsLocationIndicator;
            lhsLocationIndicator = this.getLocationIndicator();
            String rhsLocationIndicator;
            rhsLocationIndicator = that.getLocationIndicator();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "locationIndicator", lhsLocationIndicator), LocatorUtils.property(thatLocator, "locationIndicator", rhsLocationIndicator), lhsLocationIndicator, rhsLocationIndicator)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            String theLocationIndicator;
            theLocationIndicator = this.getLocationIndicator();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "locationIndicator", theLocationIndicator), currentHashCode, theLocationIndicator);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
