//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.28 at 02:58:02 PM ICT 
//


package dev.ale.fdx.entity.base;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NavaidServiceTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="NavaidServiceTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="DF"/>
 *     &lt;enumeration value="DME"/>
 *     &lt;enumeration value="ILS"/>
 *     &lt;enumeration value="ILS_DME"/>
 *     &lt;enumeration value="LOC"/>
 *     &lt;enumeration value="LOC_DME"/>
 *     &lt;enumeration value="MKR"/>
 *     &lt;enumeration value="MLS"/>
 *     &lt;enumeration value="MLS_DME"/>
 *     &lt;enumeration value="NDB"/>
 *     &lt;enumeration value="NDB_DME"/>
 *     &lt;enumeration value="NDB_MKR"/>
 *     &lt;enumeration value="SDF"/>
 *     &lt;enumeration value="TACAN"/>
 *     &lt;enumeration value="TLS"/>
 *     &lt;enumeration value="VOR"/>
 *     &lt;enumeration value="VOR_DME"/>
 *     &lt;enumeration value="VORTAC"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "NavaidServiceTypeType")
@XmlEnum
public enum NavaidServiceTypeType {


    /**
     * 
     *                   Direction Finder. 
     *                
     * 
     */
    DF,

    /**
     * 
     *                   Distance Measuring Equipment. 
     *                
     * 
     */
    DME,

    /**
     * 
     *                   Instrument Landing System 
     *                
     * 
     */
    ILS,

    /**
     * 
     *                   ILS with collocated DME. Collocation can be with the antenna or the loc. 
     *                
     * 
     */
    ILS_DME,

    /**
     * 
     *                   Localizer. 
     *                
     * 
     */
    LOC,

    /**
     * 
     *                   LOC and DME collocated. 
     *                
     * 
     */
    LOC_DME,

    /**
     * 
     *                   Marker Beacon 
     *                
     * 
     */
    MKR,

    /**
     * 
     *                   Microwave Landing System 
     *                
     * 
     */
    MLS,

    /**
     * 
     *                   MLS with collocated DME. 
     *                
     * 
     */
    MLS_DME,

    /**
     * 
     *                   Non-Directional Radio Beacon 
     *                
     * 
     */
    NDB,

    /**
     * 
     *                   NDB and DME collocated. 
     *                
     * 
     */
    NDB_DME,

    /**
     * 
     *                   Non-Directional Radio Beacon and Marker Beacon 
     *                
     * 
     */
    NDB_MKR,

    /**
     * 
     *                   Simplified Directional Facility. 
     *                
     * 
     */
    SDF,

    /**
     * 
     *                   Tactical Air Navigation Beacon 
     *                
     * 
     */
    TACAN,

    /**
     * 
     *                   Transponder Landing System 
     *                
     * 
     */
    TLS,

    /**
     * 
     *                   VHF Omni directional Radio Range. 
     *                
     * 
     */
    VOR,

    /**
     * 
     *                   VOR and DME collocated. 
     *                
     * 
     */
    VOR_DME,

    /**
     * 
     *                   VOR and TACAN collocated. 
     *                
     * 
     */
    VORTAC;

    public String value() {
        return name();
    }

    public static NavaidServiceTypeType fromValue(String v) {
        return valueOf(v);
    }

}
