//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.28 at 02:58:02 PM ICT 
//


package dev.ale.fdx.entity.base;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the aero.fixm.base._4 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FlightLevelOrAltitude_QNAME = new QName("http://www.fixm.aero/base/4.1", "FlightLevelOrAltitude");
    private final static QName _IcaoUnitReference_QNAME = new QName("http://www.fixm.aero/base/4.1", "IcaoUnitReference");
    private final static QName _TrueAirspeedChoice_QNAME = new QName("http://www.fixm.aero/base/4.1", "TrueAirspeedChoice");
    private final static QName _DesignatedPointOrNavaid_QNAME = new QName("http://www.fixm.aero/base/4.1", "DesignatedPointOrNavaid");
    private final static QName _AircraftOperator_QNAME = new QName("http://www.fixm.aero/base/4.1", "AircraftOperator");
    private final static QName _Dimensions_QNAME = new QName("http://www.fixm.aero/base/4.1", "Dimensions");
    private final static QName _VerticalDistance_QNAME = new QName("http://www.fixm.aero/base/4.1", "VerticalDistance");
    private final static QName _Measure_QNAME = new QName("http://www.fixm.aero/base/4.1", "Measure");
    private final static QName _SignificantPoint_QNAME = new QName("http://www.fixm.aero/base/4.1", "SignificantPoint");
    private final static QName _OtherReference_QNAME = new QName("http://www.fixm.aero/base/4.1", "OtherReference");
    private final static QName _GeographicalPosition_QNAME = new QName("http://www.fixm.aero/base/4.1", "GeographicalPosition");
    private final static QName _PostalAddress_QNAME = new QName("http://www.fixm.aero/base/4.1", "PostalAddress");
    private final static QName _VerticalRange_QNAME = new QName("http://www.fixm.aero/base/4.1", "VerticalRange");
    private final static QName _FlightLevelOrAltitudeChoice_QNAME = new QName("http://www.fixm.aero/base/4.1", "FlightLevelOrAltitudeChoice");
    private final static QName _TemporalRange_QNAME = new QName("http://www.fixm.aero/base/4.1", "TemporalRange");
    private final static QName _OtherUnitReference_QNAME = new QName("http://www.fixm.aero/base/4.1", "OtherUnitReference");
    private final static QName _AerodromeReference_QNAME = new QName("http://www.fixm.aero/base/4.1", "AerodromeReference");
    private final static QName _TelephoneContact_QNAME = new QName("http://www.fixm.aero/base/4.1", "TelephoneContact");
    private final static QName _RelativePoint_QNAME = new QName("http://www.fixm.aero/base/4.1", "RelativePoint");
    private final static QName _Extension_QNAME = new QName("http://www.fixm.aero/base/4.1", "Extension");
    private final static QName _PersonOrOrganization_QNAME = new QName("http://www.fixm.aero/base/4.1", "PersonOrOrganization");
    private final static QName _AtcUnitReference_QNAME = new QName("http://www.fixm.aero/base/4.1", "AtcUnitReference");
    private final static QName _Speed_QNAME = new QName("http://www.fixm.aero/base/4.1", "Speed");
    private final static QName _Extensible_QNAME = new QName("http://www.fixm.aero/base/4.1", "Extensible");
    private final static QName _ContactInformation_QNAME = new QName("http://www.fixm.aero/base/4.1", "ContactInformation");
    private final static QName _PositionPoint_QNAME = new QName("http://www.fixm.aero/base/4.1", "PositionPoint");
    private final static QName _TrueAirspeedRange_QNAME = new QName("http://www.fixm.aero/base/4.1", "TrueAirspeedRange");
    private final static QName _IcaoAerodromeReference_QNAME = new QName("http://www.fixm.aero/base/4.1", "IcaoAerodromeReference");
    private final static QName _TemporalChoice_QNAME = new QName("http://www.fixm.aero/base/4.1", "TemporalChoice");
    private final static QName _OnlineContact_QNAME = new QName("http://www.fixm.aero/base/4.1", "OnlineContact");
    private final static QName _ColourChoice_QNAME = new QName("http://www.fixm.aero/base/4.1", "ColourChoice");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: aero.fixm.base._4
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IcaoUnitReferenceType }
     * 
     */
    public IcaoUnitReferenceType createIcaoUnitReferenceType() {
        return new IcaoUnitReferenceType();
    }

    /**
     * Create an instance of {@link TrueAirspeedChoiceType }
     * 
     */
    public TrueAirspeedChoiceType createTrueAirspeedChoiceType() {
        return new TrueAirspeedChoiceType();
    }

    /**
     * Create an instance of {@link TelephoneContactType }
     * 
     */
    public TelephoneContactType createTelephoneContactType() {
        return new TelephoneContactType();
    }

    /**
     * Create an instance of {@link RelativePointType }
     * 
     */
    public RelativePointType createRelativePointType() {
        return new RelativePointType();
    }

    /**
     * Create an instance of {@link OtherReferenceType }
     * 
     */
    public OtherReferenceType createOtherReferenceType() {
        return new OtherReferenceType();
    }

    /**
     * Create an instance of {@link PositionPointType }
     * 
     */
    public PositionPointType createPositionPointType() {
        return new PositionPointType();
    }

    /**
     * Create an instance of {@link TrueAirspeedRangeType }
     * 
     */
    public TrueAirspeedRangeType createTrueAirspeedRangeType() {
        return new TrueAirspeedRangeType();
    }

    /**
     * Create an instance of {@link FlightLevelOrAltitudeChoiceType }
     * 
     */
    public FlightLevelOrAltitudeChoiceType createFlightLevelOrAltitudeChoiceType() {
        return new FlightLevelOrAltitudeChoiceType();
    }

    /**
     * Create an instance of {@link TemporalRangeType }
     * 
     */
    public TemporalRangeType createTemporalRangeType() {
        return new TemporalRangeType();
    }

    /**
     * Create an instance of {@link OtherUnitReferenceType }
     * 
     */
    public OtherUnitReferenceType createOtherUnitReferenceType() {
        return new OtherUnitReferenceType();
    }

    /**
     * Create an instance of {@link FlightLevelOrAltitudeType }
     * 
     */
    public FlightLevelOrAltitudeType createFlightLevelOrAltitudeType() {
        return new FlightLevelOrAltitudeType();
    }

    /**
     * Create an instance of {@link VerticalRangeType }
     * 
     */
    public VerticalRangeType createVerticalRangeType() {
        return new VerticalRangeType();
    }

    /**
     * Create an instance of {@link OnlineContactType }
     * 
     */
    public OnlineContactType createOnlineContactType() {
        return new OnlineContactType();
    }

    /**
     * Create an instance of {@link DimensionsType }
     * 
     */
    public DimensionsType createDimensionsType() {
        return new DimensionsType();
    }

    /**
     * Create an instance of {@link ColourChoiceType }
     * 
     */
    public ColourChoiceType createColourChoiceType() {
        return new ColourChoiceType();
    }

    /**
     * Create an instance of {@link ContactInformationType }
     * 
     */
    public ContactInformationType createContactInformationType() {
        return new ContactInformationType();
    }

    /**
     * Create an instance of {@link PostalAddressType }
     * 
     */
    public PostalAddressType createPostalAddressType() {
        return new PostalAddressType();
    }

    /**
     * Create an instance of {@link DesignatedPointOrNavaidType }
     * 
     */
    public DesignatedPointOrNavaidType createDesignatedPointOrNavaidType() {
        return new DesignatedPointOrNavaidType();
    }

    /**
     * Create an instance of {@link TemporalChoiceType }
     * 
     */
    public TemporalChoiceType createTemporalChoiceType() {
        return new TemporalChoiceType();
    }

    /**
     * Create an instance of {@link GeographicalPositionType }
     * 
     */
    public GeographicalPositionType createGeographicalPositionType() {
        return new GeographicalPositionType();
    }

    /**
     * Create an instance of {@link IcaoAerodromeReferenceType }
     * 
     */
    public IcaoAerodromeReferenceType createIcaoAerodromeReferenceType() {
        return new IcaoAerodromeReferenceType();
    }

    /**
     * Create an instance of {@link PersonOrOrganizationType }
     * 
     */
    public PersonOrOrganizationType createPersonOrOrganizationType() {
        return new PersonOrOrganizationType();
    }

    /**
     * Create an instance of {@link AircraftOperatorType }
     * 
     */
    public AircraftOperatorType createAircraftOperatorType() {
        return new AircraftOperatorType();
    }

    /**
     * Create an instance of {@link RadioactivityType }
     * 
     */
    public RadioactivityType createRadioactivityType() {
        return new RadioactivityType();
    }

    /**
     * Create an instance of {@link WeightType }
     * 
     */
    public WeightType createWeightType() {
        return new WeightType();
    }

    /**
     * Create an instance of {@link DistanceType }
     * 
     */
    public DistanceType createDistanceType() {
        return new DistanceType();
    }

    /**
     * Create an instance of {@link GroundSpeedType }
     * 
     */
    public GroundSpeedType createGroundSpeedType() {
        return new GroundSpeedType();
    }

    /**
     * Create an instance of {@link IndicatedAirspeedType }
     * 
     */
    public IndicatedAirspeedType createIndicatedAirspeedType() {
        return new IndicatedAirspeedType();
    }

    /**
     * Create an instance of {@link WindSpeedType }
     * 
     */
    public WindSpeedType createWindSpeedType() {
        return new WindSpeedType();
    }

    /**
     * Create an instance of {@link GloballyUniqueFlightIdentifierType }
     * 
     */
    public GloballyUniqueFlightIdentifierType createGloballyUniqueFlightIdentifierType() {
        return new GloballyUniqueFlightIdentifierType();
    }

    /**
     * Create an instance of {@link AngleType }
     * 
     */
    public AngleType createAngleType() {
        return new AngleType();
    }

    /**
     * Create an instance of {@link VerticalRateType }
     * 
     */
    public VerticalRateType createVerticalRateType() {
        return new VerticalRateType();
    }

    /**
     * Create an instance of {@link SsrCodeType }
     * 
     */
    public SsrCodeType createSsrCodeType() {
        return new SsrCodeType();
    }

    /**
     * Create an instance of {@link LengthType }
     * 
     */
    public LengthType createLengthType() {
        return new LengthType();
    }

    /**
     * Create an instance of {@link HeightType }
     * 
     */
    public HeightType createHeightType() {
        return new HeightType();
    }

    /**
     * Create an instance of {@link PressureType }
     * 
     */
    public PressureType createPressureType() {
        return new PressureType();
    }

    /**
     * Create an instance of {@link AltitudeType }
     * 
     */
    public AltitudeType createAltitudeType() {
        return new AltitudeType();
    }

    /**
     * Create an instance of {@link WindDirectionType }
     * 
     */
    public WindDirectionType createWindDirectionType() {
        return new WindDirectionType();
    }

    /**
     * Create an instance of {@link FlightLevelType }
     * 
     */
    public FlightLevelType createFlightLevelType() {
        return new FlightLevelType();
    }

    /**
     * Create an instance of {@link TrueAirspeedType }
     * 
     */
    public TrueAirspeedType createTrueAirspeedType() {
        return new TrueAirspeedType();
    }

    /**
     * Create an instance of {@link VolumeType }
     * 
     */
    public VolumeType createVolumeType() {
        return new VolumeType();
    }

    /**
     * Create an instance of {@link TemperatureType }
     * 
     */
    public TemperatureType createTemperatureType() {
        return new TemperatureType();
    }

    /**
     * Create an instance of {@link BearingType }
     * 
     */
    public BearingType createBearingType() {
        return new BearingType();
    }

    /**
     * Create an instance of {@link FrequencyType }
     * 
     */
    public FrequencyType createFrequencyType() {
        return new FrequencyType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlightLevelOrAltitudeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.1", name = "FlightLevelOrAltitude", substitutionHeadNamespace = "http://www.fixm.aero/base/4.1", substitutionHeadName = "Extensible")
    public JAXBElement<FlightLevelOrAltitudeType> createFlightLevelOrAltitude(FlightLevelOrAltitudeType value) {
        return new JAXBElement<FlightLevelOrAltitudeType>(_FlightLevelOrAltitude_QNAME, FlightLevelOrAltitudeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IcaoUnitReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.1", name = "IcaoUnitReference", substitutionHeadNamespace = "http://www.fixm.aero/base/4.1", substitutionHeadName = "Extensible")
    public JAXBElement<IcaoUnitReferenceType> createIcaoUnitReference(IcaoUnitReferenceType value) {
        return new JAXBElement<IcaoUnitReferenceType>(_IcaoUnitReference_QNAME, IcaoUnitReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TrueAirspeedChoiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.1", name = "TrueAirspeedChoice", substitutionHeadNamespace = "http://www.fixm.aero/base/4.1", substitutionHeadName = "Extensible")
    public JAXBElement<TrueAirspeedChoiceType> createTrueAirspeedChoice(TrueAirspeedChoiceType value) {
        return new JAXBElement<TrueAirspeedChoiceType>(_TrueAirspeedChoice_QNAME, TrueAirspeedChoiceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DesignatedPointOrNavaidType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.1", name = "DesignatedPointOrNavaid", substitutionHeadNamespace = "http://www.fixm.aero/base/4.1", substitutionHeadName = "Extensible")
    public JAXBElement<DesignatedPointOrNavaidType> createDesignatedPointOrNavaid(DesignatedPointOrNavaidType value) {
        return new JAXBElement<DesignatedPointOrNavaidType>(_DesignatedPointOrNavaid_QNAME, DesignatedPointOrNavaidType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AircraftOperatorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.1", name = "AircraftOperator", substitutionHeadNamespace = "http://www.fixm.aero/base/4.1", substitutionHeadName = "Extensible")
    public JAXBElement<AircraftOperatorType> createAircraftOperator(AircraftOperatorType value) {
        return new JAXBElement<AircraftOperatorType>(_AircraftOperator_QNAME, AircraftOperatorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DimensionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.1", name = "Dimensions")
    public JAXBElement<DimensionsType> createDimensions(DimensionsType value) {
        return new JAXBElement<DimensionsType>(_Dimensions_QNAME, DimensionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.1", name = "VerticalDistance", substitutionHeadNamespace = "http://www.fixm.aero/base/4.1", substitutionHeadName = "Measure")
    public JAXBElement<Double> createVerticalDistance(Double value) {
        return new JAXBElement<Double>(_VerticalDistance_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.1", name = "Measure")
    public JAXBElement<Double> createMeasure(Double value) {
        return new JAXBElement<Double>(_Measure_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignificantPointType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.1", name = "SignificantPoint", substitutionHeadNamespace = "http://www.fixm.aero/base/4.1", substitutionHeadName = "Extensible")
    public JAXBElement<SignificantPointType> createSignificantPoint(SignificantPointType value) {
        return new JAXBElement<SignificantPointType>(_SignificantPoint_QNAME, SignificantPointType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OtherReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.1", name = "OtherReference", substitutionHeadNamespace = "http://www.fixm.aero/base/4.1", substitutionHeadName = "Extensible")
    public JAXBElement<OtherReferenceType> createOtherReference(OtherReferenceType value) {
        return new JAXBElement<OtherReferenceType>(_OtherReference_QNAME, OtherReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeographicalPositionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.1", name = "GeographicalPosition", substitutionHeadNamespace = "http://www.fixm.aero/base/4.1", substitutionHeadName = "Extensible")
    public JAXBElement<GeographicalPositionType> createGeographicalPosition(GeographicalPositionType value) {
        return new JAXBElement<GeographicalPositionType>(_GeographicalPosition_QNAME, GeographicalPositionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PostalAddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.1", name = "PostalAddress", substitutionHeadNamespace = "http://www.fixm.aero/base/4.1", substitutionHeadName = "Extensible")
    public JAXBElement<PostalAddressType> createPostalAddress(PostalAddressType value) {
        return new JAXBElement<PostalAddressType>(_PostalAddress_QNAME, PostalAddressType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VerticalRangeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.1", name = "VerticalRange", substitutionHeadNamespace = "http://www.fixm.aero/base/4.1", substitutionHeadName = "Extensible")
    public JAXBElement<VerticalRangeType> createVerticalRange(VerticalRangeType value) {
        return new JAXBElement<VerticalRangeType>(_VerticalRange_QNAME, VerticalRangeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlightLevelOrAltitudeChoiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.1", name = "FlightLevelOrAltitudeChoice", substitutionHeadNamespace = "http://www.fixm.aero/base/4.1", substitutionHeadName = "Extensible")
    public JAXBElement<FlightLevelOrAltitudeChoiceType> createFlightLevelOrAltitudeChoice(FlightLevelOrAltitudeChoiceType value) {
        return new JAXBElement<FlightLevelOrAltitudeChoiceType>(_FlightLevelOrAltitudeChoice_QNAME, FlightLevelOrAltitudeChoiceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TemporalRangeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.1", name = "TemporalRange", substitutionHeadNamespace = "http://www.fixm.aero/base/4.1", substitutionHeadName = "Extensible")
    public JAXBElement<TemporalRangeType> createTemporalRange(TemporalRangeType value) {
        return new JAXBElement<TemporalRangeType>(_TemporalRange_QNAME, TemporalRangeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OtherUnitReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.1", name = "OtherUnitReference", substitutionHeadNamespace = "http://www.fixm.aero/base/4.1", substitutionHeadName = "Extensible")
    public JAXBElement<OtherUnitReferenceType> createOtherUnitReference(OtherUnitReferenceType value) {
        return new JAXBElement<OtherUnitReferenceType>(_OtherUnitReference_QNAME, OtherUnitReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AerodromeReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.1", name = "AerodromeReference", substitutionHeadNamespace = "http://www.fixm.aero/base/4.1", substitutionHeadName = "Extensible")
    public JAXBElement<AerodromeReferenceType> createAerodromeReference(AerodromeReferenceType value) {
        return new JAXBElement<AerodromeReferenceType>(_AerodromeReference_QNAME, AerodromeReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TelephoneContactType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.1", name = "TelephoneContact", substitutionHeadNamespace = "http://www.fixm.aero/base/4.1", substitutionHeadName = "Extensible")
    public JAXBElement<TelephoneContactType> createTelephoneContact(TelephoneContactType value) {
        return new JAXBElement<TelephoneContactType>(_TelephoneContact_QNAME, TelephoneContactType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelativePointType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.1", name = "RelativePoint", substitutionHeadNamespace = "http://www.fixm.aero/base/4.1", substitutionHeadName = "Extensible")
    public JAXBElement<RelativePointType> createRelativePoint(RelativePointType value) {
        return new JAXBElement<RelativePointType>(_RelativePoint_QNAME, RelativePointType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.1", name = "Extension")
    public JAXBElement<ExtensionType> createExtension(ExtensionType value) {
        return new JAXBElement<ExtensionType>(_Extension_QNAME, ExtensionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonOrOrganizationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.1", name = "PersonOrOrganization", substitutionHeadNamespace = "http://www.fixm.aero/base/4.1", substitutionHeadName = "Extensible")
    public JAXBElement<PersonOrOrganizationType> createPersonOrOrganization(PersonOrOrganizationType value) {
        return new JAXBElement<PersonOrOrganizationType>(_PersonOrOrganization_QNAME, PersonOrOrganizationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AtcUnitReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.1", name = "AtcUnitReference", substitutionHeadNamespace = "http://www.fixm.aero/base/4.1", substitutionHeadName = "Extensible")
    public JAXBElement<AtcUnitReferenceType> createAtcUnitReference(AtcUnitReferenceType value) {
        return new JAXBElement<AtcUnitReferenceType>(_AtcUnitReference_QNAME, AtcUnitReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.1", name = "Speed", substitutionHeadNamespace = "http://www.fixm.aero/base/4.1", substitutionHeadName = "Measure")
    public JAXBElement<Double> createSpeed(Double value) {
        return new JAXBElement<Double>(_Speed_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensibleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.1", name = "Extensible")
    public JAXBElement<ExtensibleType> createExtensible(ExtensibleType value) {
        return new JAXBElement<ExtensibleType>(_Extensible_QNAME, ExtensibleType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContactInformationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.1", name = "ContactInformation", substitutionHeadNamespace = "http://www.fixm.aero/base/4.1", substitutionHeadName = "Extensible")
    public JAXBElement<ContactInformationType> createContactInformation(ContactInformationType value) {
        return new JAXBElement<ContactInformationType>(_ContactInformation_QNAME, ContactInformationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PositionPointType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.1", name = "PositionPoint", substitutionHeadNamespace = "http://www.fixm.aero/base/4.1", substitutionHeadName = "Extensible")
    public JAXBElement<PositionPointType> createPositionPoint(PositionPointType value) {
        return new JAXBElement<PositionPointType>(_PositionPoint_QNAME, PositionPointType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TrueAirspeedRangeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.1", name = "TrueAirspeedRange", substitutionHeadNamespace = "http://www.fixm.aero/base/4.1", substitutionHeadName = "Extensible")
    public JAXBElement<TrueAirspeedRangeType> createTrueAirspeedRange(TrueAirspeedRangeType value) {
        return new JAXBElement<TrueAirspeedRangeType>(_TrueAirspeedRange_QNAME, TrueAirspeedRangeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IcaoAerodromeReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.1", name = "IcaoAerodromeReference", substitutionHeadNamespace = "http://www.fixm.aero/base/4.1", substitutionHeadName = "Extensible")
    public JAXBElement<IcaoAerodromeReferenceType> createIcaoAerodromeReference(IcaoAerodromeReferenceType value) {
        return new JAXBElement<IcaoAerodromeReferenceType>(_IcaoAerodromeReference_QNAME, IcaoAerodromeReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TemporalChoiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.1", name = "TemporalChoice", substitutionHeadNamespace = "http://www.fixm.aero/base/4.1", substitutionHeadName = "Extensible")
    public JAXBElement<TemporalChoiceType> createTemporalChoice(TemporalChoiceType value) {
        return new JAXBElement<TemporalChoiceType>(_TemporalChoice_QNAME, TemporalChoiceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OnlineContactType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.1", name = "OnlineContact", substitutionHeadNamespace = "http://www.fixm.aero/base/4.1", substitutionHeadName = "Extensible")
    public JAXBElement<OnlineContactType> createOnlineContact(OnlineContactType value) {
        return new JAXBElement<OnlineContactType>(_OnlineContact_QNAME, OnlineContactType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ColourChoiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.1", name = "ColourChoice", substitutionHeadNamespace = "http://www.fixm.aero/base/4.1", substitutionHeadName = "Extensible")
    public JAXBElement<ColourChoiceType> createColourChoice(ColourChoiceType value) {
        return new JAXBElement<ColourChoiceType>(_ColourChoice_QNAME, ColourChoiceType.class, null, value);
    }

}
