//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.28 at 02:58:02 PM ICT 
//


package dev.ale.fdx.entity.base;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * 
 *             A reference to an area control centre, approach control unit or aerodrome control 
 *             tower using the ATC unit name and optionally its geographical position, if no ICAO 
 *             location indicator is available. [FIXM] 
 *          
 * 
 * <p>Java class for OtherUnitReferenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OtherUnitReferenceType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fixm.aero/base/4.1}AtcUnitReferenceType">
 *       &lt;sequence>
 *         &lt;element name="position" type="{http://www.fixm.aero/base/4.1}GeographicalPositionType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="atcUnitNameOrAlternate" type="{http://www.fixm.aero/base/4.1}TextNameType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OtherUnitReferenceType", propOrder = {
    "position"
})
@Entity(name = "OtherUnitReferenceType")
@Table(name = "OTHERUNITREFERENCETYPE")
public class OtherUnitReferenceType
    extends AtcUnitReferenceType
    implements Equals, HashCode
{

    protected GeographicalPositionType position;
    @XmlAttribute(name = "atcUnitNameOrAlternate")
    protected String atcUnitNameOrAlternate;

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link GeographicalPositionType }
     *     
     */
    @ManyToOne(targetEntity = GeographicalPositionType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "POSITION__OTHERUNITREFERENCE_0")
    public GeographicalPositionType getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeographicalPositionType }
     *     
     */
    public void setPosition(GeographicalPositionType value) {
        this.position = value;
    }

    /**
     * Gets the value of the atcUnitNameOrAlternate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "ATCUNITNAMEORALTERNATE", length = 60)
    public String getAtcUnitNameOrAlternate() {
        return atcUnitNameOrAlternate;
    }

    /**
     * Sets the value of the atcUnitNameOrAlternate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAtcUnitNameOrAlternate(String value) {
        this.atcUnitNameOrAlternate = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof OtherUnitReferenceType)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final OtherUnitReferenceType that = ((OtherUnitReferenceType) object);
        {
            GeographicalPositionType lhsPosition;
            lhsPosition = this.getPosition();
            GeographicalPositionType rhsPosition;
            rhsPosition = that.getPosition();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "position", lhsPosition), LocatorUtils.property(thatLocator, "position", rhsPosition), lhsPosition, rhsPosition)) {
                return false;
            }
        }
        {
            String lhsAtcUnitNameOrAlternate;
            lhsAtcUnitNameOrAlternate = this.getAtcUnitNameOrAlternate();
            String rhsAtcUnitNameOrAlternate;
            rhsAtcUnitNameOrAlternate = that.getAtcUnitNameOrAlternate();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "atcUnitNameOrAlternate", lhsAtcUnitNameOrAlternate), LocatorUtils.property(thatLocator, "atcUnitNameOrAlternate", rhsAtcUnitNameOrAlternate), lhsAtcUnitNameOrAlternate, rhsAtcUnitNameOrAlternate)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            GeographicalPositionType thePosition;
            thePosition = this.getPosition();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "position", thePosition), currentHashCode, thePosition);
        }
        {
            String theAtcUnitNameOrAlternate;
            theAtcUnitNameOrAlternate = this.getAtcUnitNameOrAlternate();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "atcUnitNameOrAlternate", theAtcUnitNameOrAlternate), currentHashCode, theAtcUnitNameOrAlternate);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
