//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.28 at 02:58:02 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.fixm.aero/base/4.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package dev.ale.fdx.entity.base;
