//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.28 at 02:58:02 PM ICT 
//


package dev.ale.fdx.entity.base;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SsrModeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SsrModeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="A"/>
 *     &lt;enumeration value="C"/>
 *     &lt;enumeration value="S"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SsrModeType")
@XmlEnum
public enum SsrModeType {


    /**
     * 
     *                   Indicates Secondary Surveillance Radar (SSR) is operating in Transponder-Mode A. 
     *                   
     *                
     * 
     */
    A,

    /**
     * 
     *                   Indicates Secondary Surveillance Radar (SSR) Transponder-Mode A and Mode C. 
     *                
     * 
     */
    C,

    /**
     * 
     *                   Indicates Secondary Surveillance Radar (SSR) Transponder-Mode S. 
     *                
     * 
     */
    S;

    public String value() {
        return name();
    }

    public static SsrModeType fromValue(String v) {
        return valueOf(v);
    }

}
