//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.28 at 02:58:02 PM ICT 
//


package dev.ale.fdx.entity.base;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TelecomNetworkTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TelecomNetworkTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AFTN"/>
 *     &lt;enumeration value="INTERNET"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TelecomNetworkTypeType")
@XmlEnum
public enum TelecomNetworkTypeType {


    /**
     * 
     *                   The data interchange in the AFS is performed by the Aeronautical Fixed Telecommunications 
     *                   Network, AFTN. This is a message handling network running according to ICAO Standards 
     *                   documented in Annex 10 to the ICAO Convention.[AIXM] 
     *                
     * 
     */
    AFTN,

    /**
     * 
     *                   The Internet is a worldwide, publicly accessible series of interconnected computer 
     *                   networks that transmit data by packet switching using the standard Internet Protocol 
     *                   (IP). 
     *                   The usage of this value indicates that a URL will be provided for the linkage property 
     *                   in OnlineContact. 
     *                
     * 
     */
    INTERNET;

    public String value() {
        return name();
    }

    public static TelecomNetworkTypeType fromValue(String v) {
        return valueOf(v);
    }

}
