//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.28 at 02:58:02 PM ICT 
//


package dev.ale.fdx.entity.base;

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.XMLGregorianCalendarAsDateTime;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.XmlAdapterUtils;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * 
 *             Allows to specify either a time or a time range. 
 *          
 * 
 * <p>Java class for TemporalChoiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TemporalChoiceType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fixm.aero/base/4.1}ExtensibleType">
 *       &lt;choice>
 *         &lt;element name="temporalRange" type="{http://www.fixm.aero/base/4.1}TemporalRangeType" minOccurs="0"/>
 *         &lt;element name="timeValue" type="{http://www.fixm.aero/base/4.1}TimeType" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TemporalChoiceType", propOrder = {
    "temporalRange",
    "timeValue"
})
@Entity(name = "TemporalChoiceType")
@Table(name = "TEMPORALCHOICETYPE")
public class TemporalChoiceType
    extends ExtensibleType
    implements Equals, HashCode
{

    protected TemporalRangeType temporalRange;
    protected XMLGregorianCalendar timeValue;

    /**
     * Gets the value of the temporalRange property.
     * 
     * @return
     *     possible object is
     *     {@link TemporalRangeType }
     *     
     */
    @ManyToOne(targetEntity = TemporalRangeType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "TEMPORALRANGE_TEMPORALCHOICE_0")
    public TemporalRangeType getTemporalRange() {
        return temporalRange;
    }

    /**
     * Sets the value of the temporalRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemporalRangeType }
     *     
     */
    public void setTemporalRange(TemporalRangeType value) {
        this.temporalRange = value;
    }

    /**
     * Gets the value of the timeValue property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Transient
    public XMLGregorianCalendar getTimeValue() {
        return timeValue;
    }

    /**
     * Sets the value of the timeValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeValue(XMLGregorianCalendar value) {
        this.timeValue = value;
    }

    @Basic
    @Column(name = "TIMEVALUEITEM")
    @Temporal(TemporalType.TIMESTAMP)
    public Date getTimeValueItem() {
        return XmlAdapterUtils.unmarshall(XMLGregorianCalendarAsDateTime.class, this.getTimeValue());
    }

    public void setTimeValueItem(Date target) {
        setTimeValue(XmlAdapterUtils.marshall(XMLGregorianCalendarAsDateTime.class, target));
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof TemporalChoiceType)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final TemporalChoiceType that = ((TemporalChoiceType) object);
        {
            TemporalRangeType lhsTemporalRange;
            lhsTemporalRange = this.getTemporalRange();
            TemporalRangeType rhsTemporalRange;
            rhsTemporalRange = that.getTemporalRange();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "temporalRange", lhsTemporalRange), LocatorUtils.property(thatLocator, "temporalRange", rhsTemporalRange), lhsTemporalRange, rhsTemporalRange)) {
                return false;
            }
        }
        {
            XMLGregorianCalendar lhsTimeValue;
            lhsTimeValue = this.getTimeValue();
            XMLGregorianCalendar rhsTimeValue;
            rhsTimeValue = that.getTimeValue();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "timeValue", lhsTimeValue), LocatorUtils.property(thatLocator, "timeValue", rhsTimeValue), lhsTimeValue, rhsTimeValue)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            TemporalRangeType theTemporalRange;
            theTemporalRange = this.getTemporalRange();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "temporalRange", theTemporalRange), currentHashCode, theTemporalRange);
        }
        {
            XMLGregorianCalendar theTimeValue;
            theTimeValue = this.getTimeValue();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "timeValue", theTimeValue), currentHashCode, theTimeValue);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
