//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.28 at 02:58:02 PM ICT 
//


package dev.ale.fdx.entity.base;

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.XMLGregorianCalendarAsDateTime;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.XmlAdapterUtils;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * 
 *             Temporal range resulting from assigned speed range. 
 *          
 * 
 * <p>Java class for TemporalRangeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TemporalRangeType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fixm.aero/base/4.1}ExtensibleType">
 *       &lt;attribute name="earliest" type="{http://www.fixm.aero/base/4.1}TimeType" />
 *       &lt;attribute name="latest" type="{http://www.fixm.aero/base/4.1}TimeType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TemporalRangeType")
@Entity(name = "TemporalRangeType")
@Table(name = "TEMPORALRANGETYPE")
public class TemporalRangeType
    extends ExtensibleType
    implements Equals, HashCode
{

    @XmlAttribute(name = "earliest")
    protected XMLGregorianCalendar earliest;
    @XmlAttribute(name = "latest")
    protected XMLGregorianCalendar latest;

    /**
     * Gets the value of the earliest property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Transient
    public XMLGregorianCalendar getEarliest() {
        return earliest;
    }

    /**
     * Sets the value of the earliest property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEarliest(XMLGregorianCalendar value) {
        this.earliest = value;
    }

    /**
     * Gets the value of the latest property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Transient
    public XMLGregorianCalendar getLatest() {
        return latest;
    }

    /**
     * Sets the value of the latest property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLatest(XMLGregorianCalendar value) {
        this.latest = value;
    }

    @Basic
    @Column(name = "EARLIESTITEM")
    @Temporal(TemporalType.TIMESTAMP)
    public Date getEarliestItem() {
        return XmlAdapterUtils.unmarshall(XMLGregorianCalendarAsDateTime.class, this.getEarliest());
    }

    public void setEarliestItem(Date target) {
        setEarliest(XmlAdapterUtils.marshall(XMLGregorianCalendarAsDateTime.class, target));
    }

    @Basic
    @Column(name = "LATESTITEM")
    @Temporal(TemporalType.TIMESTAMP)
    public Date getLatestItem() {
        return XmlAdapterUtils.unmarshall(XMLGregorianCalendarAsDateTime.class, this.getLatest());
    }

    public void setLatestItem(Date target) {
        setLatest(XmlAdapterUtils.marshall(XMLGregorianCalendarAsDateTime.class, target));
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof TemporalRangeType)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final TemporalRangeType that = ((TemporalRangeType) object);
        {
            XMLGregorianCalendar lhsEarliest;
            lhsEarliest = this.getEarliest();
            XMLGregorianCalendar rhsEarliest;
            rhsEarliest = that.getEarliest();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "earliest", lhsEarliest), LocatorUtils.property(thatLocator, "earliest", rhsEarliest), lhsEarliest, rhsEarliest)) {
                return false;
            }
        }
        {
            XMLGregorianCalendar lhsLatest;
            lhsLatest = this.getLatest();
            XMLGregorianCalendar rhsLatest;
            rhsLatest = that.getLatest();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "latest", lhsLatest), LocatorUtils.property(thatLocator, "latest", rhsLatest), lhsLatest, rhsLatest)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            XMLGregorianCalendar theEarliest;
            theEarliest = this.getEarliest();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "earliest", theEarliest), currentHashCode, theEarliest);
        }
        {
            XMLGregorianCalendar theLatest;
            theLatest = this.getLatest();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "latest", theLatest), currentHashCode, theLatest);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
