//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.28 at 02:58:02 PM ICT 
//


package dev.ale.fdx.entity.flight;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.XMLGregorianCalendarAsDateTime;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.XmlAdapterUtils;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;

import dev.ale.fdx.entity.base.AerodromeReferenceType;
import dev.ale.fdx.entity.base.ExtensibleType;


/**
 * 
 *             Information about the actual arrival of the flight. [FIXM] 
 *          
 * 
 * <p>Java class for ArrivalType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArrivalType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fixm.aero/base/4.1}ExtensibleType">
 *       &lt;sequence>
 *         &lt;element name="aerodrome" type="{http://www.fixm.aero/base/4.1}AerodromeReferenceType" minOccurs="0"/>
 *         &lt;element name="arrivalAerodrome" type="{http://www.fixm.aero/base/4.1}AerodromeReferenceType" minOccurs="0"/>
 *         &lt;element name="destinationAerodrome" type="{http://www.fixm.aero/base/4.1}AerodromeReferenceType" minOccurs="0"/>
 *         &lt;element name="destinationAerodromeAlternate" type="{http://www.fixm.aero/base/4.1}AerodromeReferenceType" maxOccurs="2" minOccurs="0"/>
 *         &lt;element name="reclearanceInFlight" type="{http://www.fixm.aero/flight/4.1}ReclearanceInFlightType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="actualTimeOfArrival" type="{http://www.fixm.aero/base/4.1}TimeType" />
 *       &lt;attribute name="airportSlotIdentification" type="{http://www.fixm.aero/base/4.1}AirportSlotIdentificationType" />
 *       &lt;attribute name="runwayDirection" type="{http://www.fixm.aero/base/4.1}RunwayDirectionDesignatorType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrivalType", propOrder = {
    "aerodrome",
    "arrivalAerodrome",
    "destinationAerodrome",
    "destinationAerodromeAlternate",
    "reclearanceInFlight"
})
@Entity(name = "ArrivalType")
@Table(name = "ARRIVALTYPE")
public class ArrivalType
    extends ExtensibleType
    implements Equals, HashCode
{

    protected AerodromeReferenceType aerodrome;
    protected AerodromeReferenceType arrivalAerodrome;
    protected AerodromeReferenceType destinationAerodrome;
    protected List<AerodromeReferenceType> destinationAerodromeAlternate;
    protected ReclearanceInFlightType reclearanceInFlight;
    @XmlAttribute(name = "actualTimeOfArrival")
    protected XMLGregorianCalendar actualTimeOfArrival;
    @XmlAttribute(name = "airportSlotIdentification")
    protected String airportSlotIdentification;
    @XmlAttribute(name = "runwayDirection")
    protected String runwayDirection;

    /**
     * Gets the value of the aerodrome property.
     * 
     * @return
     *     possible object is
     *     {@link AerodromeReferenceType }
     *     
     */
    @ManyToOne(targetEntity = AerodromeReferenceType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "AERODROME_ARRIVALTYPE_HJID")
    public AerodromeReferenceType getAerodrome() {
        return aerodrome;
    }

    /**
     * Sets the value of the aerodrome property.
     * 
     * @param value
     *     allowed object is
     *     {@link AerodromeReferenceType }
     *     
     */
    public void setAerodrome(AerodromeReferenceType value) {
        this.aerodrome = value;
    }

    /**
     * Gets the value of the arrivalAerodrome property.
     * 
     * @return
     *     possible object is
     *     {@link AerodromeReferenceType }
     *     
     */
    @ManyToOne(targetEntity = AerodromeReferenceType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "ARRIVALAERODROME_ARRIVALTYPE_0")
    public AerodromeReferenceType getArrivalAerodrome() {
        return arrivalAerodrome;
    }

    /**
     * Sets the value of the arrivalAerodrome property.
     * 
     * @param value
     *     allowed object is
     *     {@link AerodromeReferenceType }
     *     
     */
    public void setArrivalAerodrome(AerodromeReferenceType value) {
        this.arrivalAerodrome = value;
    }

    /**
     * Gets the value of the destinationAerodrome property.
     * 
     * @return
     *     possible object is
     *     {@link AerodromeReferenceType }
     *     
     */
    @ManyToOne(targetEntity = AerodromeReferenceType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "DESTINATIONAERODROME_ARRIVAL_0")
    public AerodromeReferenceType getDestinationAerodrome() {
        return destinationAerodrome;
    }

    /**
     * Sets the value of the destinationAerodrome property.
     * 
     * @param value
     *     allowed object is
     *     {@link AerodromeReferenceType }
     *     
     */
    public void setDestinationAerodrome(AerodromeReferenceType value) {
        this.destinationAerodrome = value;
    }

    /**
     * Gets the value of the destinationAerodromeAlternate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the destinationAerodromeAlternate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDestinationAerodromeAlternate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AerodromeReferenceType }
     * 
     * 
     */
    @OneToMany(targetEntity = AerodromeReferenceType.class, cascade = {
        CascadeType.ALL
    }, fetch = FetchType.LAZY)
    @JoinColumn(name = "DESTINATIONAERODROMEALTERNAT_0")
    @LazyCollection(LazyCollectionOption.FALSE)
    public List<AerodromeReferenceType> getDestinationAerodromeAlternate() {
        if (destinationAerodromeAlternate == null) {
            destinationAerodromeAlternate = new ArrayList<AerodromeReferenceType>();
        }
        return this.destinationAerodromeAlternate;
    }

    /**
     * 
     * 
     */
    public void setDestinationAerodromeAlternate(List<AerodromeReferenceType> destinationAerodromeAlternate) {
        this.destinationAerodromeAlternate = destinationAerodromeAlternate;
    }

    /**
     * Gets the value of the reclearanceInFlight property.
     * 
     * @return
     *     possible object is
     *     {@link ReclearanceInFlightType }
     *     
     */
    @ManyToOne(targetEntity = ReclearanceInFlightType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "RECLEARANCEINFLIGHT_ARRIVALT_0")
    public ReclearanceInFlightType getReclearanceInFlight() {
        return reclearanceInFlight;
    }

    /**
     * Sets the value of the reclearanceInFlight property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReclearanceInFlightType }
     *     
     */
    public void setReclearanceInFlight(ReclearanceInFlightType value) {
        this.reclearanceInFlight = value;
    }

    /**
     * Gets the value of the actualTimeOfArrival property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Transient
    public XMLGregorianCalendar getActualTimeOfArrival() {
        return actualTimeOfArrival;
    }

    /**
     * Sets the value of the actualTimeOfArrival property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setActualTimeOfArrival(XMLGregorianCalendar value) {
        this.actualTimeOfArrival = value;
    }

    /**
     * Gets the value of the airportSlotIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "AIRPORTSLOTIDENTIFICATION", length = 10)
    public String getAirportSlotIdentification() {
        return airportSlotIdentification;
    }

    /**
     * Sets the value of the airportSlotIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirportSlotIdentification(String value) {
        this.airportSlotIdentification = value;
    }

    /**
     * Gets the value of the runwayDirection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "RUNWAYDIRECTION", length = 4096)
    public String getRunwayDirection() {
        return runwayDirection;
    }

    /**
     * Sets the value of the runwayDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRunwayDirection(String value) {
        this.runwayDirection = value;
    }

    @Basic
    @Column(name = "ACTUALTIMEOFARRIVALITEM")
    @Temporal(TemporalType.TIMESTAMP)
    public Date getActualTimeOfArrivalItem() {
        return XmlAdapterUtils.unmarshall(XMLGregorianCalendarAsDateTime.class, this.getActualTimeOfArrival());
    }

    public void setActualTimeOfArrivalItem(Date target) {
        setActualTimeOfArrival(XmlAdapterUtils.marshall(XMLGregorianCalendarAsDateTime.class, target));
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof ArrivalType)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final ArrivalType that = ((ArrivalType) object);
        {
            AerodromeReferenceType lhsAerodrome;
            lhsAerodrome = this.getAerodrome();
            AerodromeReferenceType rhsAerodrome;
            rhsAerodrome = that.getAerodrome();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "aerodrome", lhsAerodrome), LocatorUtils.property(thatLocator, "aerodrome", rhsAerodrome), lhsAerodrome, rhsAerodrome)) {
                return false;
            }
        }
        {
            AerodromeReferenceType lhsArrivalAerodrome;
            lhsArrivalAerodrome = this.getArrivalAerodrome();
            AerodromeReferenceType rhsArrivalAerodrome;
            rhsArrivalAerodrome = that.getArrivalAerodrome();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "arrivalAerodrome", lhsArrivalAerodrome), LocatorUtils.property(thatLocator, "arrivalAerodrome", rhsArrivalAerodrome), lhsArrivalAerodrome, rhsArrivalAerodrome)) {
                return false;
            }
        }
        {
            AerodromeReferenceType lhsDestinationAerodrome;
            lhsDestinationAerodrome = this.getDestinationAerodrome();
            AerodromeReferenceType rhsDestinationAerodrome;
            rhsDestinationAerodrome = that.getDestinationAerodrome();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "destinationAerodrome", lhsDestinationAerodrome), LocatorUtils.property(thatLocator, "destinationAerodrome", rhsDestinationAerodrome), lhsDestinationAerodrome, rhsDestinationAerodrome)) {
                return false;
            }
        }
        {
            List<AerodromeReferenceType> lhsDestinationAerodromeAlternate;
            lhsDestinationAerodromeAlternate = (((this.destinationAerodromeAlternate!= null)&&(!this.destinationAerodromeAlternate.isEmpty()))?this.getDestinationAerodromeAlternate():null);
            List<AerodromeReferenceType> rhsDestinationAerodromeAlternate;
            rhsDestinationAerodromeAlternate = (((that.destinationAerodromeAlternate!= null)&&(!that.destinationAerodromeAlternate.isEmpty()))?that.getDestinationAerodromeAlternate():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "destinationAerodromeAlternate", lhsDestinationAerodromeAlternate), LocatorUtils.property(thatLocator, "destinationAerodromeAlternate", rhsDestinationAerodromeAlternate), lhsDestinationAerodromeAlternate, rhsDestinationAerodromeAlternate)) {
                return false;
            }
        }
        {
            ReclearanceInFlightType lhsReclearanceInFlight;
            lhsReclearanceInFlight = this.getReclearanceInFlight();
            ReclearanceInFlightType rhsReclearanceInFlight;
            rhsReclearanceInFlight = that.getReclearanceInFlight();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "reclearanceInFlight", lhsReclearanceInFlight), LocatorUtils.property(thatLocator, "reclearanceInFlight", rhsReclearanceInFlight), lhsReclearanceInFlight, rhsReclearanceInFlight)) {
                return false;
            }
        }
        {
            XMLGregorianCalendar lhsActualTimeOfArrival;
            lhsActualTimeOfArrival = this.getActualTimeOfArrival();
            XMLGregorianCalendar rhsActualTimeOfArrival;
            rhsActualTimeOfArrival = that.getActualTimeOfArrival();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "actualTimeOfArrival", lhsActualTimeOfArrival), LocatorUtils.property(thatLocator, "actualTimeOfArrival", rhsActualTimeOfArrival), lhsActualTimeOfArrival, rhsActualTimeOfArrival)) {
                return false;
            }
        }
        {
            String lhsAirportSlotIdentification;
            lhsAirportSlotIdentification = this.getAirportSlotIdentification();
            String rhsAirportSlotIdentification;
            rhsAirportSlotIdentification = that.getAirportSlotIdentification();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "airportSlotIdentification", lhsAirportSlotIdentification), LocatorUtils.property(thatLocator, "airportSlotIdentification", rhsAirportSlotIdentification), lhsAirportSlotIdentification, rhsAirportSlotIdentification)) {
                return false;
            }
        }
        {
            String lhsRunwayDirection;
            lhsRunwayDirection = this.getRunwayDirection();
            String rhsRunwayDirection;
            rhsRunwayDirection = that.getRunwayDirection();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "runwayDirection", lhsRunwayDirection), LocatorUtils.property(thatLocator, "runwayDirection", rhsRunwayDirection), lhsRunwayDirection, rhsRunwayDirection)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            AerodromeReferenceType theAerodrome;
            theAerodrome = this.getAerodrome();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "aerodrome", theAerodrome), currentHashCode, theAerodrome);
        }
        {
            AerodromeReferenceType theArrivalAerodrome;
            theArrivalAerodrome = this.getArrivalAerodrome();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "arrivalAerodrome", theArrivalAerodrome), currentHashCode, theArrivalAerodrome);
        }
        {
            AerodromeReferenceType theDestinationAerodrome;
            theDestinationAerodrome = this.getDestinationAerodrome();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "destinationAerodrome", theDestinationAerodrome), currentHashCode, theDestinationAerodrome);
        }
        {
            List<AerodromeReferenceType> theDestinationAerodromeAlternate;
            theDestinationAerodromeAlternate = (((this.destinationAerodromeAlternate!= null)&&(!this.destinationAerodromeAlternate.isEmpty()))?this.getDestinationAerodromeAlternate():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "destinationAerodromeAlternate", theDestinationAerodromeAlternate), currentHashCode, theDestinationAerodromeAlternate);
        }
        {
            ReclearanceInFlightType theReclearanceInFlight;
            theReclearanceInFlight = this.getReclearanceInFlight();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "reclearanceInFlight", theReclearanceInFlight), currentHashCode, theReclearanceInFlight);
        }
        {
            XMLGregorianCalendar theActualTimeOfArrival;
            theActualTimeOfArrival = this.getActualTimeOfArrival();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "actualTimeOfArrival", theActualTimeOfArrival), currentHashCode, theActualTimeOfArrival);
        }
        {
            String theAirportSlotIdentification;
            theAirportSlotIdentification = this.getAirportSlotIdentification();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "airportSlotIdentification", theAirportSlotIdentification), currentHashCode, theAirportSlotIdentification);
        }
        {
            String theRunwayDirection;
            theRunwayDirection = this.getRunwayDirection();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "runwayDirection", theRunwayDirection), currentHashCode, theRunwayDirection);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
