//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.28 at 02:58:02 PM ICT 
//


package dev.ale.fdx.entity.flight;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;

import dev.ale.fdx.entity.base.ExtensibleType;


/**
 * 
 *             A container of flight identifying data. [FIXM] 
 *          
 * 
 * <p>Java class for FlightIdentificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FlightIdentificationType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fixm.aero/base/4.1}ExtensibleType">
 *       &lt;attribute name="aircraftIdentification" type="{http://www.fixm.aero/base/4.1}AircraftIdentificationType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlightIdentificationType")
@Entity(name = "FlightIdentificationType")
@Table(name = "FLIGHTIDENTIFICATIONTYPE")
public class FlightIdentificationType
    extends ExtensibleType
    implements Equals, HashCode
{

    @XmlAttribute(name = "aircraftIdentification")
    protected String aircraftIdentification;

    /**
     * Gets the value of the aircraftIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "AIRCRAFTIDENTIFICATION", length = 4096)
    public String getAircraftIdentification() {
        return aircraftIdentification;
    }

    /**
     * Sets the value of the aircraftIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAircraftIdentification(String value) {
        this.aircraftIdentification = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof FlightIdentificationType)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final FlightIdentificationType that = ((FlightIdentificationType) object);
        {
            String lhsAircraftIdentification;
            lhsAircraftIdentification = this.getAircraftIdentification();
            String rhsAircraftIdentification;
            rhsAircraftIdentification = that.getAircraftIdentification();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "aircraftIdentification", lhsAircraftIdentification), LocatorUtils.property(thatLocator, "aircraftIdentification", rhsAircraftIdentification), lhsAircraftIdentification, rhsAircraftIdentification)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            String theAircraftIdentification;
            theAircraftIdentification = this.getAircraftIdentification();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "aircraftIdentification", theAircraftIdentification), currentHashCode, theAircraftIdentification);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
