//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.28 at 02:58:02 PM ICT 
//


package dev.ale.fdx.entity.flight;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;

import dev.ale.fdx.entity.base.FlightLevelOrAltitudeType;


/**
 * 
 *             Describes a new planned altitude or level at the specified point at which the change 
 *             is planned to commence.  (May also describe a point at which the altitude or level 
 *             change is planned to be attained.) 
 *          
 * 
 * <p>Java class for LevelChangeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LevelChangeType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fixm.aero/flight/4.1}AbstractRouteChangeType">
 *       &lt;sequence>
 *         &lt;element name="level" type="{http://www.fixm.aero/base/4.1}FlightLevelOrAltitudeType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="activation" type="{http://www.fixm.aero/flight/4.1}ActivationType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LevelChangeType", propOrder = {
    "level"
})
@Entity(name = "LevelChangeType")
@Table(name = "LEVELCHANGETYPE")
public class LevelChangeType
    extends AbstractRouteChangeType
    implements Equals, HashCode
{

    protected FlightLevelOrAltitudeType level;
    @XmlAttribute(name = "activation")
    protected ActivationType activation;

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link FlightLevelOrAltitudeType }
     *     
     */
    @ManyToOne(targetEntity = FlightLevelOrAltitudeType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "LEVEL__LEVELCHANGETYPE_HJID")
    public FlightLevelOrAltitudeType getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightLevelOrAltitudeType }
     *     
     */
    public void setLevel(FlightLevelOrAltitudeType value) {
        this.level = value;
    }

    /**
     * Gets the value of the activation property.
     * 
     * @return
     *     possible object is
     *     {@link ActivationType }
     *     
     */
    @Basic
    @Column(name = "ACTIVATION", length = 255)
    @Enumerated(EnumType.STRING)
    public ActivationType getActivation() {
        return activation;
    }

    /**
     * Sets the value of the activation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActivationType }
     *     
     */
    public void setActivation(ActivationType value) {
        this.activation = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof LevelChangeType)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final LevelChangeType that = ((LevelChangeType) object);
        {
            FlightLevelOrAltitudeType lhsLevel;
            lhsLevel = this.getLevel();
            FlightLevelOrAltitudeType rhsLevel;
            rhsLevel = that.getLevel();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "level", lhsLevel), LocatorUtils.property(thatLocator, "level", rhsLevel), lhsLevel, rhsLevel)) {
                return false;
            }
        }
        {
            ActivationType lhsActivation;
            lhsActivation = this.getActivation();
            ActivationType rhsActivation;
            rhsActivation = that.getActivation();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "activation", lhsActivation), LocatorUtils.property(thatLocator, "activation", rhsActivation), lhsActivation, rhsActivation)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            FlightLevelOrAltitudeType theLevel;
            theLevel = this.getLevel();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "level", theLevel), currentHashCode, theLevel);
        }
        {
            ActivationType theActivation;
            theActivation = this.getActivation();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "activation", theActivation), currentHashCode, theActivation);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
