//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.28 at 02:58:02 PM ICT 
//


package dev.ale.fdx.entity.flight;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TypeOfFlightType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TypeOfFlightType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="M"/>
 *     &lt;enumeration value="G"/>
 *     &lt;enumeration value="N"/>
 *     &lt;enumeration value="S"/>
 *     &lt;enumeration value="X"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TypeOfFlightType")
@XmlEnum
public enum TypeOfFlightType {


    /**
     * 
     *                   Military [ICAO Doc 4444, Item 8] 
     *                
     * 
     */
    M,

    /**
     * 
     *                   General aviation [ICAO Doc 4444, Item 8] 
     *                
     * 
     */
    G,

    /**
     * 
     *                   Non-scheduled air transport operation [ICAO Doc 4444, Item 8] 
     *                
     * 
     */
    N,

    /**
     * 
     *                   Scheduled air service [ICAO Doc 4444, Item 8] 
     *                
     * 
     */
    S,

    /**
     * 
     *                   Other than any of the defined categories above. [ICAO Doc 4444, Item 8] 
     *                
     * 
     */
    X;

    public String value() {
        return name();
    }

    public static TypeOfFlightType fromValue(String v) {
        return valueOf(v);
    }

}
